
from typing import Dict
from shybox.runner_toolkit.namelist.lib_utils_dataclass import M, D, Var





# namelist template for HMC version 3.2.0
namelist_hmc_330: Dict[str, Dict[str, Var]] = {

    "HMC_Parameters": {
        "dUc": D(20),
        "dUh": D(1.5),
        "dCt": D(0.5),
        "dCf": D(0.02),
        "dCPI": D(0.3),
        "dCN": D(60.01),
        "dWS": D(3.678e-09),
        "dWDL": D(3.678e-09),
        "dFrac": D(0.0),
        "dWTableHbr": D(500),
        "dKSatRatio": D(1),
        "dSlopeMax": D(70),
        "dSoil_ksat_infilt": D(3.5),
        "dSoil_ksat_drain": D(3.5),
        "dSoil_vmax": D(500),
        "dWTable_ksath": D(1),
        "dWTable_init": D(0.1),
        "sDomainName": M(),
    },

    "HMC_Namelist": {
        "iFlagDebugSet": D(1),
        "iFlagDebugLevel": D(3),

        "iFlagTypeData_Static": D(1),
        "iFlagTypeData_Forcing_Gridded": D(2),
        "iFlagTypeData_Forcing_Point": D(1),
        "iFlagTypeData_Forcing_TimeSeries": D(1),
        "iFlagTypeData_Updating_Gridded": D(2),
        "iFlagTypeData_Output_Gridded": D(2),
        "iFlagTypeData_Output_Point": D(1),
        "iFlagTypeData_Output_TimeSeries": D(1),
        "iFlagTypeData_State_Gridded": D(2),
        "iFlagTypeData_State_Point": D(1),
        "iFlagTypeData_Restart_Gridded": D(2),
        "iFlagTypeData_Restart_Point": D(1),

        "iFlagOs": D(10),
        "iFlagFlowDeep": D(1),
        "iFlagRestart": D(1),
        "iFlagVarDtPhysConv": D(1),
        "iFlagSnow": D(0),
        "iFlagSnowAssim": D(0),
        "iFlagSMAssim": D(0),
        "iFlagLAI": D(0),
        "iFlagAlbedo": D(0),
        "iFlagCoeffRes": D(1),
        "iFlagWS": D(0),
        "iFlagWDL": D(0),
        "iFlagReleaseMass": D(1),
        "iFlagCType": D(1),
        "iFlagFrac": D(0),
        "iFlagDynVeg": D(1),
        "iFlagFlood": D(0),
        "iFlagEnergyBalance": D(1),
        "iFlagSoilParamsType": D(1),
        "iFlagInfiltRateVariable": D(2),
        "iFlagBetaET": D(1),

        "a1dGeoForcing": D([-9999.0, -9999.0]),
        "a1dResForcing": D([-9999.0, -9999.0]),
        "a1iDimsForcing": D([-9999, -9999]),

        "iSimLength": M(),
        "iDtModel": M(),

        "iDtPhysMethod": D(1),
        "iDtPhysConv": D(50),
        "a1dDemStep": D([1, 10, 100, 1000]),
        "a1dIntStep": D([1, 5, 25, 600]),
        "a1dDtStep": D([1, 6, 6, 60]),
        "a1dDtRatioStep": D([3, 3, 3, 2]),

        "iDtData_Forcing": M(),
        "iDtData_Updating": M(),
        "iDtData_Output_Gridded": M(),
        "iDtData_Output_Point": M(),
        "iDtData_State_Gridded": M(),
        "iDtData_State_Point": M(),

        "iActiveData_Output_Generic": D(2),
        "iActiveData_Output_Flooding": D(0),
        "iActiveData_Output_Snow": D(0),
        "iAccumData_Output_Hour": D(23),

        "iScaleFactor": D(10),
        "iTcMax": D(-9999),
        "iTVeg": D(720),

        "sTimeStart": M(),
        "sTimeRestart": M(),

        "sPathData_Static_Gridded": M(),
        "sPathData_Static_Point": M(),
        "sPathData_Forcing_Gridded": M(),
        "sPathData_Forcing_Point": M(),
        "sPathData_Forcing_TimeSeries": M(),
        "sPathData_Updating_Gridded": M(),
        "sPathData_Output_Gridded": M(),
        "sPathData_Output_Point": M(),
        "sPathData_Output_TimeSeries": M(),
        "sPathData_State_Gridded": M(),
        "sPathData_State_Point": M(),
        "sPathData_Restart_Gridded": M(),
        "sPathData_Restart_Point": M(),
    },

    "HMC_Snow": {
        "a1dArctUp": D([3.0, 4.5, 3.0, 4.0]),
        "a1dExpRhoLow": D([0.0333, 0.0222, 0.0250, 0.0333]),
        "a1dExpRhoHigh": D([0.0714]*4),
        "a1dAltRange": D([1500.0, 2000.0, 2500.0, 2500.0]),
        "iGlacierValue": D(2),
        "dRhoSnowFresh": D(100),
        "dRhoSnowMax": D(400),
        "dSnowQualityThr": D(0.3),
        "dMeltingTRef": D(1),
    },

    "HMC_Constants": {
        "a1dAlbedoMonthly": D([0.18,0.17,0.16,0.15,0.15,0.15,0.15,0.16,0.16,0.17,0.17,0.18]),
        "a1dLAIMonthly": D([4.0]*12),

        "dWTableHMin": D(10.0),
        "dWTableHUSoil": D(100.0),
        "dWTableHUChannel": D(5.0),
        "dWTableSlopeBM": D(0.08),
        "dWTableHOBedRock": D(25.0),

        "dRateMin": D(0.01),
        "dRateRescaling": D(1.0),
        "dBc": D(0.5),
        "dWTLossMax": D(0.25),
        "dPowVarInfiltRate": D(7),

        "dTRef": D(273.15),
        "iTdeepShift": D(2),
        "a1dCHMonthly": D([-7.3, -7.3, -5.8, -5.8, -5.8, -4.8,
                           -4.8, -4.8, -4.8, -5.9, -5.9, -7.3]),
        "dEpsS": D(0.96),
        "dSigma": D(5.576e-08),
        "dBFMin": D(0.1),
        "dBFMax": D(0.9),
        "dLSTDeltaMax": D(40),

        "dZRef": D(3.0),
        "dG": D(9.81),
        "dCp": D(1004.0),
        "dRd": D(287.0),

        "dRhoS": D(2700),
        "dRhoW": D(1000),
        "dCpS": D(733),
        "dCpW": D(4186),
        "dKq": D(7.7),
        "dKw": D(0.57),
        "dKo": D(4),
        "dPorS": D(0.4),
        "dFqS": D(0.5),

        "dTV": D(0.95),
        "dDamSpillH": D(0.4),

        "dSMGain": D(0.45),
    },

    "HMC_Command": {
        "sCommandZipFile": D("gzip -f filenameunzip > LogZip.txt"),
        "sCommandUnzipFile": D("gunzip -c filenamezip > filenameunzip"),
        "sCommandRemoveFile": D("rm filename"),
        "sCommandCreateFolder": D("mkdir -p path"),
    },

    "HMC_Info": {
        "sReleaseVersion": D("3.3.0"),
        "sAuthorNames": D("Delogu F., Silvestro F., Gabellani S., Libertino A., Ercolani G."),
        "sReleaseDate": D("2025/11/14"),
    },
}

# namelist template for HMC version 3.2.0
namelist_hmc_320: Dict[str, Dict[str, Var]] = {

    "HMC_Parameters": {
        "dUc": D(20),
        "dUh": D(1.5),
        "dCt": D(0.5),
        "dCf": D(0.02),
        "dCPI": D(0.3),
        "dCN": D(60.01),
        "dWS": D(3.6780000000000003e-09),
        "dWDL": D(3.6780000000000003e-09),
        "dFrac": D(0.0),
        "dWTableHbr": D(500),
        "dKSatRatio": D(1),
        "dSlopeMax": D(70),
        "dSoil_ksat_infilt": D(3.5),
        "dSoil_ksat_drain": D(3.5),
        "dSoil_vmax": D(500),
        "dWtable_ksath": D(1),
        "sDomainName": M(),
    },

    "HMC_Namelist": {
        "iFlagDebugSet": D(1),
        "iFlagDebugLevel": D(3),

        "iFlagTypeData_Static": D(1),
        "iFlagTypeData_Forcing_Gridded": D(2),
        "iFlagTypeData_Forcing_Point": D(1),
        "iFlagTypeData_Forcing_TimeSeries": D(1),
        "iFlagTypeData_Updating_Gridded": D(2),
        "iFlagTypeData_Output_Gridded": D(2),
        "iFlagTypeData_Output_Point": D(1),
        "iFlagTypeData_Output_TimeSeries": D(1),
        "iFlagTypeData_State_Gridded": D(2),
        "iFlagTypeData_State_Point": D(1),
        "iFlagTypeData_Restart_Gridded": D(2),
        "iFlagTypeData_Restart_Point": D(1),

        "iFlagOs": D(10),
        "iFlagFlowDeep": D(1),
        "iFlagRestart": D(1),
        "iFlagVarDtPhysConv": D(1),
        "iFlagSnow": D(0),
        "iFlagSnowAssim": D(0),
        "iFlagSMAssim": D(0),
        "iFlagLAI": D(0),
        "iFlagAlbedo": D(0),
        "iFlagCoeffRes": D(1),
        "iFlagWS": D(0),
        "iFlagWDL": D(0),
        "iFlagReleaseMass": D(1),
        "iFlagCType": D(1),
        "iFlagFrac": D(0),
        "iFlagDynVeg": D(1),
        "iFlagFlood": D(0),
        "iFlagEnergyBalance": D(1),
        "iFlagSoilParamsType": D(1),
        "iFlagInfiltRateVariable": D(2),
        "iFlagBetaET": D(1),

        "a1dGeoForcing": D([-9999.0, -9999.0]),
        "a1dResForcing": D([-9999.0, -9999.0]),
        "a1iDimsForcing": D([-9999, -9999]),

        "iSimLength": M(),
        "iDtModel": M(),

        "iDtPhysMethod": D(1),
        "iDtPhysConv": D(50),
        "a1dDemStep": D([1, 10, 100, 1000]),
        "a1dIntStep": D([1, 5, 25, 600]),
        "a1dDtStep": D([1, 6, 6, 60]),
        "a1dDtRatioStep": D([3, 3, 3, 2]),

        "iDtData_Forcing": M(),
        "iDtData_Updating": M(),
        "iDtData_Output_Gridded": M(),
        "iDtData_Output_Point": M(),
        "iDtData_State_Gridded": M(),
        "iDtData_State_Point": M(),

        "iActiveData_Output_Generic": D(2),
        "iActiveData_Output_Flooding": D(0),
        "iActiveData_Output_Snow": D(0),
        "iAccumData_Output_Hour": D(23),

        "iScaleFactor": D(10),
        "iTcMax": D(-9999),
        "iTVeg": D(720),

        "sTimeStart": M(),
        "sTimeRestart": M(),

        "sPathData_Static_Gridded": M(),
        "sPathData_Static_Point": M(),
        "sPathData_Forcing_Gridded": M(),
        "sPathData_Forcing_Point": M(),
        "sPathData_Forcing_TimeSeries": M(),
        "sPathData_Updating_Gridded": M(),
        "sPathData_Output_Gridded": M(),
        "sPathData_Output_Point": M(),
        "sPathData_Output_TimeSeries": M(),
        "sPathData_State_Gridded": M(),
        "sPathData_State_Point": M(),
        "sPathData_Restart_Gridded": M(),
        "sPathData_Restart_Point": M(),
    },

    "HMC_Snow": {
        "a1dArctUp": D([3.0, 4.5, 3.0, 4.0]),
        "a1dExpRhoLow": D([0.0333, 0.0222, 0.0250, 0.0333]),
        "a1dExpRhoHigh": D([0.0714, 0.0714, 0.0714, 0.0714]),
        "a1dAltRange": D([1500.0, 2000.0, 2500.0, 2500.0]),
        "iGlacierValue": D(2),
        "dRhoSnowFresh": D(100),
        "dRhoSnowMax": D(400),
        "dSnowQualityThr": D(0.3),
        "dMeltingTRef": D(1),
    },

    "HMC_Constants": {
        "a1dAlbedoMonthly": D([0.18, 0.17, 0.16, 0.15, 0.15, 0.15,
                               0.15, 0.16, 0.16, 0.17, 0.17, 0.18]),
        "a1dLAIMonthly": D([4.0] * 12),

        "dWTableHMin": D(10.0),
        "dWTableHUSoil": D(100.0),
        "dWTableHUChannel": D(5.0),
        "dWTableSlopeBM": D(0.08),
        "dWTableHOBedRock": D(25.0),

        "dRateMin": D(0.01),
        "dRateRescaling": D(1.0),
        "dBc": D(0.5),
        "dWTLossMax": D(0.25),
        "dPowVarInfiltRate": D(7),

        "dTRef": D(273.15),
        "iTdeepShift": D(2),
        "a1dCHMonthly": D([-7.3, -7.3, -5.8, -5.8, -5.8, -4.8,
                           -4.8, -4.8, -4.8, -5.9, -5.9, -7.3]),
        "dEpsS": D(0.96),
        "dSigma": D(0.00000005576),
        "dBFMin": D(0.1),
        "dBFMax": D(0.9),
        "dLSTDeltaMax": D(40),

        "dZRef": D(3.0),
        "dG": D(9.81),
        "dCp": D(1004.0),
        "dRd": D(287.0),

        "dRhoS": D(2700),
        "dRhoW": D(1000),
        "dCpS": D(733),
        "dCpW": D(4186),
        "dKq": D(7.7),
        "dKw": D(0.57),
        "dKo": D(4),
        "dPorS": D(0.4),
        "dFqS": D(0.5),

        "dTV": D(0.95),
        "dDamSpillH": D(0.4),

        "dSMGain": D(0.45),
    },

    "HMC_Command": {
        "sCommandZipFile": D("gzip -f filenameunzip > LogZip.txt"),
        "sCommandUnzipFile": D("gunzip -c filenamezip > filenameunzip"),
        "sCommandRemoveFile": D("rm filename"),
        "sCommandCreateFolder": D("mkdir -p path"),
    },

    "HMC_Info": {
        "sReleaseVersion": D("3.2.0"),
        "sAuthorNames": D("Delogu F., Silvestro F., Gabellani S., Libertino A., Ercolani G."),
        "sReleaseDate": D("2025/01/01"),
    },
}

# namelist template for HMC version 3.1.6
namelist_hmc_316: Dict[str, Dict[str, Var]] = {

    "HMC_Parameters": {
        "dUc": D(20),
        "dUh": D(1.5),
        "dCt": D(0.5),
        "dCf": D(0.02),
        "dCPI": D(0.3),
        "dCN": D(60.01),
        "dWS": D(3.6780000000000003e-09),
        "dWDL": D(3.6780000000000003e-09),
        "dFrac": D(0.0),
        "dWTableHbr": D(500),
        "dKSatRatio": D(1),
        "dSlopeMax": D(70),
        "sDomainName": M(),
    },

    "HMC_Namelist": {
        "iFlagDebugSet": D(0),
        "iFlagDebugLevel": D(3),

        "iFlagTypeData_Static": D(1),
        "iFlagTypeData_Forcing_Gridded": D(2),
        "iFlagTypeData_Forcing_Point": D(1),
        "iFlagTypeData_Forcing_TimeSeries": D(1),
        "iFlagTypeData_Updating_Gridded": D(2),
        "iFlagTypeData_Output_Gridded": D(2),
        "iFlagTypeData_Output_Point": D(1),
        "iFlagTypeData_Output_TimeSeries": D(1),
        "iFlagTypeData_State_Gridded": D(2),
        "iFlagTypeData_State_Point": D(1),
        "iFlagTypeData_Restart_Gridded": D(2),
        "iFlagTypeData_Restart_Point": D(1),

        "iFlagOs": D(10),
        "iFlagFlowDeep": D(1),
        "iFlagRestart": D(1),
        "iFlagVarDtPhysConv": D(1),
        "iFlagSnow": D(0),
        "iFlagSnowAssim": D(0),
        "iFlagSMAssim": D(0),
        "iFlagLAI": D(0),
        "iFlagAlbedo": D(0),
        "iFlagCoeffRes": D(1),
        "iFlagWS": D(0),
        "iFlagWDL": D(0),
        "iFlagReleaseMass": D(1),
        "iFlagCType": D(1),
        "iFlagFrac": D(0),
        "iFlagDynVeg": D(1),
        "iFlagFlood": D(0),
        "iFlagEnergyBalance": D(1),

        "a1dGeoForcing": D([-9999.0, -9999.0]),
        "a1dResForcing": D([-9999.0, -9999.0]),
        "a1iDimsForcing": D([-9999, -9999]),

        "iSimLength": M(),
        "iDtModel": M(),

        "iDtPhysMethod": D(1),
        "iDtPhysConv": D(50),
        "a1dDemStep": D([1, 10, 100, 1000]),
        "a1dIntStep": D([1, 5, 25, 600]),
        "a1dDtStep": D([1, 6, 6, 60]),
        "a1dDtRatioStep": D([3, 3, 3, 2]),

        "iDtData_Forcing": M(),
        "iDtData_Updating": M(),
        "iDtData_Output_Gridded": M(),
        "iDtData_Output_Point": M(),
        "iDtData_State_Gridded": M(),
        "iDtData_State_Point": M(),

        "iActiveData_Output_Generic": D(2),
        "iActiveData_Output_Flooding": D(0),
        "iActiveData_Output_Snow": D(0),
        "iAccumData_Output_Hour": D(23),

        "iScaleFactor": D(10),
        "iTcMax": D(-9999),
        "iTVeg": D(720),

        "sTimeStart": M(),
        "sTimeRestart": M(),

        "sPathData_Static_Gridded": M(),
        "sPathData_Static_Point": M(),
        "sPathData_Forcing_Gridded": M(),
        "sPathData_Forcing_Point": M(),
        "sPathData_Forcing_TimeSeries": M(),
        "sPathData_Updating_Gridded": M(),
        "sPathData_Output_Gridded": M(),
        "sPathData_Output_Point": M(),
        "sPathData_Output_TimeSeries": M(),
        "sPathData_State_Gridded": M(),
        "sPathData_State_Point": M(),
        "sPathData_Restart_Gridded": M(),
        "sPathData_Restart_Point": M(),
    },

    "HMC_Snow": {
        "a1dArctUp": D([3.0, 4.5, 3.0, 4.0]),
        "a1dExpRhoLow": D([0.0333, 0.0222, 0.0250, 0.0333]),
        "a1dExpRhoHigh": D([0.0714, 0.0714, 0.0714, 0.0714]),
        "a1dAltRange": D([1500.0, 2000.0, 2500.0, 2500.0]),
        "iGlacierValue": D(2),
        "dRhoSnowFresh": D(100),
        "dRhoSnowMax": D(400),
        "dSnowQualityThr": D(0.3),
        "dMeltingTRef": D(1),
    },

    "HMC_Constants": {
        "a1dAlbedoMonthly": D([0.18, 0.17, 0.16, 0.15, 0.15, 0.15,
                               0.15, 0.16, 0.16, 0.17, 0.17, 0.18]),
        "a1dLAIMonthly": D([4.0] * 12),

        "dWTableHMin": D(10.0),
        "dWTableHUSoil": D(100.0),
        "dWTableHUChannel": D(5.0),
        "dWTableSlopeBM": D(0.08),
        "dWTableHOBedRock": D(25.0),

        "dRateMin": D(0.01),
        "dBc": D(0.5),
        "dWTLossMax": D(0.25),

        "dTRef": D(273.15),
        "iTdeepShift": D(2),
        "a1dCHMonthly": D([-7.3, -7.3, -5.8, -5.8, -5.8, -4.8,
                           -4.8, -4.8, -4.8, -5.9, -5.9, -7.3]),
        "dEpsS": D(0.96),
        "dSigma": D(0.00000005576),
        "dBFMin": D(0.1),
        "dBFMax": D(0.9),
        "dLSTDeltaMax": D(40),

        "dZRef": D(3.0),
        "dG": D(9.81),
        "dCp": D(1004.0),
        "dRd": D(287.0),

        "dRhoS": D(2700),
        "dRhoW": D(1000),
        "dCpS": D(733),
        "dCpW": D(4186),
        "dKq": D(7.7),
        "dKw": D(0.57),
        "dKo": D(4),
        "dPorS": D(0.4),
        "dFqS": D(0.5),

        "dTV": D(0.95),
        "dDamSpillH": D(0.4),

        "dSMGain": D(0.45),
    },

    "HMC_Command": {
        "sCommandZipFile": D("gzip -f filenameunzip > LogZip.txt"),
        "sCommandUnzipFile": D("gunzip -c filenamezip > filenameunzip"),
        "sCommandRemoveFile": D("rm filename"),
        "sCommandCreateFolder": D("mkdir -p path"),
    },

    "HMC_Info": {
        "sReleaseVersion": D("3.1.6"),
        "sAuthorNames": D("Delogu F., Silvestro F., Gabellani S., Libertino A., Ercolani G."),
        "sReleaseDate": D("2025/01/01"),
    },
}
